# Generated by Django 3.1.3 on 2020-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rsc_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_pwd', models.CharField(max_length=30)),
                ('admin_name', models.CharField(max_length=10)),
                ('admin_contact', models.CharField(max_length=30)),
                ('admin_rsc', models.PositiveSmallIntegerField()),
                ('admin_ip', models.CharField(max_length=16)),
            ],
        ),
    ]
