# Generated by Django 3.1.3 on 2020-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_date', models.DateField()),
                ('bg_image', models.ImageField(upload_to='bg', verbose_name='background')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_date', models.DateField()),
                ('cm_content', models.TextField()),
                ('cm_image', models.ImageField(blank=True, null=True, upload_to='cm', verbose_name='community')),
            ],
        ),
        migrations.CreateModel(
            name='portrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptr_date', models.DateField()),
                ('ptr_image', models.ImageField(upload_to='ptr', verbose_name='portrait')),
            ],
        ),
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thn_date', models.DateField()),
                ('thn_image', models.ImageField(upload_to='thn', verbose_name='thumbnail')),
            ],
        ),
    ]
