# Generated by Django 3.1.3 on 2020-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_date', models.DateField()),
                ('sche_title', models.CharField(max_length=20)),
                ('sche_content', models.TextField()),
                ('sche_rsc', models.URLField()),
                ('admin', models.EmailField(max_length=254)),
            ],
        ),
    ]
