# Generated by Django 3.1.3 on 2020-12-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sche_rsc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
