# Generated by Django 3.1.3 on 2020-12-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20201213_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vid_lines_trans',
            new_name='vid_dial_trans',
        ),
    ]
